"""Add driver assignment to parcels

Revision ID: 7636afbb2c2a
Revises: 48cf77c86489
Create Date: 2026-09-21 15:15:16.799018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7636afbb2c2a'
down_revision = '48cf77c86489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_driver_id')

    # ### end Alembic commands ###
